### ISSUE TITLE
Git tags naming issue on OpenUPM

### ISSUE THREAD

**Issue by favoyang** [DTeruel/Toolnity#2]
Hi @DTeruel,

You may notice that `com.dteruel.toolnity@2.0.0` didn't get processed by OpenUPM pipelines. The tag `2.0.0` has been marked as an `Invalid Git Tag` (duplicated version).

https://openupm.com/packages/com.dteruel.toolnity/?subPage=pipelines 

![image](https://user-images.githubusercontent.com/125390/194719943-c110c4f4-2888-4c69-b36b-f1192b6b4397.png)

Because the pipeline filtered the Git tag list by prefix `toolnity`, and found 3 candidates for version 2.0.0.

- `toolnity/2.0.0`
- `toolnity/collections/2.0.0`
- `toolnity/custom_buttons/2.0.0`

It didn't know which one to take, and picked a random one and ignore others. In this case, the `toolnity/custom_buttons/2.0.0` has been taken.

To avoid the ambiguous tag, I suggest you try one of the Git tag patterns below:
- `toolnity/2.0.0`, `toolnity-collections/2.0.0`, `toolnity-custom_buttons/2.0.0`. Then update the Git tag prefix to `toolnity/` on OpenUPM.
- `toolnity/2.0.0`, `collections/2.0.0`, `custom_buttons/2.0.0`. keep the Git tag prefix to `toolnity` no change on OpenUPM.

Either way will solve the issue.

**Comment by DTeruel** [comment]
Hey! The good one should be 'toolnity/2.0.0'. the other ones were tests until I understood how it works with the subpackages.

But anyway, I'm not sure if it will work since this is not a package anymore. Is a Unity project with different subpackages inside, and this project is used to test all the packages and have the "main index" in there.
Thanks!

**Comment by favoyang** [comment]
> Hey! The good one should be 'toolnity/2.0.0'. the other ones were tests until I understood how it works with the subpackages.

You need to choose one of the git tag naming pattern mentioned above to achieve this (help our pipelines to detect the correct git tag)

If the "index" package is no longer needed, please consider removing from the openupm.

**Comment by DTeruel** [comment]
It's not a package anymore but I'd like to keep the oldest versions for
compatibility woth older projects.
The only thing I want know it's to avoid new builds (or waiting for an
specific tag as 'toolnity').
It's that possible?

**Comment by favoyang** [comment]
We don't have a flag for an "archived" repository yet. It's something good to have for an archived GitHub repository or a manual flag for one sub-package of monorepo like this.

For now, you can consider a workaround
- Remove the openupm package meta file (YAML), which will keep your packages on the registry, but only the web page is removed.
- Or, change the gitTagPrefix to something like `non-existed-prefix`, to stop the pipeline from tracking for new versions.

**Comment by DTeruel** [comment]
The second option is what I did for now. :)

Thanks for your help!
